### PR TITLE
Fix #1045. Ensure line plot displays integer-valued data items in log display.

### LINKED ISSUE #1045: Line plot with log display does not handle integer data properly
Make an integer-valued 1D data item. Set resulting line plot to log display. Fails.

### PR DESCRIPTION
**Pull request by cmeyer**

### CODE REVIEW

**Comment by ndellby** [comment]
Why do we care about integer data?

(email by Outlook, if I can find it)


-Bruker Confidential-

________________________________
From: Chris Meyer ***@***.***>
Sent: Tuesday, May 14, 2024 4:54:01 PM
To: nion-software/nionswift ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nion-software/nionswift] Fix #1045. Ensure line plot displays integer-valued data items in log display. (PR #1046)

**EXTERNAL EMAIL**
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/nion-software/nionswift/pull/1046

Commit Summary

  *   0358123<https://github.com/nion-software/nionswift/pull/1046/commits/0358123db1fbb3c8d011fa381ee1c9d47ca50392> Fix #1045. Ensure line plot displays integer-valued data items in log display.

File Changes

(2 files<https://github.com/nion-software/nionswift/pull/1046/files>)

  *   M nion/swift/LineGraphCanvasItem.py<https://github.com/nion-software/nionswift/pull/1046/files#diff-fc43e746fd3782b16ec910753de2c1975a18d9ada87e062f480b68fc50f6680d> (4)
  *   M nion/swift/test/LineGraphCanvasItem_test.py<https://github.com/nion-software/nionswift/pull/1046/files#diff-8b5d45db2d3169b494e49234f06bc7d349b445ab42f9b51732c81b39b7e75522> (8)

Patch Links:

  *   https://github.com/nion-software/nionswift/pull/1046.patch
  *   https://github.com/nion-software/nionswift/pull/1046.diff

**Comment by cmeyer** [comment]
> Why do we care about integer data? (email by Outlook, if I can find it)

Data items can contain numpy arrays of any data type, including integer. The line plot was not displaying and showing a stack trace.

**Review by Tiomat85 — COMMENTED** [review]
Fix makes sense, forcing it to float if it isn't.  
Question on your unit test though, you are asserting the min is <0.0, yet your lowest data point is 1.

**Comment by cmeyer** [comment]
> Fix makes sense, forcing it to float if it isn't. Question on your unit test though, you are asserting the min is <0.0, yet your lowest data point is 1.

I added some explanation to the code (force pushed).

**Pull request merged**
